sudo: required
language: node_js
node_js:
  - "6.9.5"

branches:
  only:
    - master

before_script:
  - npm install

script:
  - npm test
  - npm test-api

notifications:
  email:
    on_failure: change
    on_success: change
