sudo: required
language: node_js
node_js:
  - "6.9.5"

branches:
  only:
    - master

before_script:
  - npm install

script:
  - npm test
  - npm run test-api

after_success:
  - npm run coverage
  - npm run report-coverage

notifications:
  email:
    on_failure: change
    on_success: change
